<!DOCTYPE html><!--文档html5格式定义-->
<html lang="en">
<head>
    <!--html5的页面字符设置-->
    <meta charset=UTF-8>
    <title>Title</title>
    <style>
        body{
            margin:0;
            padding:0;
            background:#f5f5dc;
        }
        section{
            width:660px;
            height:500px;
            margin:0 auto;
        }
        header{
            width:100%;
        }
    </style>
</head>
<body>
<!--使用header定义页面头部-->
<header>
    <h2>标题</h2>
    <!--使用nav定义页面导航条-->
    <nav>
        <ul>
            <li>首页</li>
            <li>首页</li>
            <li>首页</li>
            <li>首页</li>
        </ul>
    </nav>
</header>
<!--使用section定义页面主体区-->
<section>
    <!--使用article定义文章区-->
    <article>
        <!--使用header定义文章头-->
        <header>
            header
        </header>
        <!--使用aside定义文章侧边-->
        <aside>
            aside
        </aside>
        <p>文章内容</p>
        <p>文章内容</p>
        <!--使用footer定义文章底部信息-->
        <footer>
            footer
        </footer>
    </article>
    <!--使用article定义文章区-->
    <article>
        <!--使用header定义文章头-->
        <header>
            header
        </header>
        <!--使用aside定义文章侧边-->
        <aside>
            aside
        </aside>
        <p>文章内容</p>
        <p>文章内容</p>
        <!--使用footer定义文章底部信息-->
        <footer>
            footer
        </footer>
    </article>
    <!--使用article定义文章区-->
    <article>
        <!--使用header定义文章头-->
        <header>
            header
        </header>
        <!--使用aside定义文章侧边-->
        <aside>
            aside
        </aside>
        <p>文章内容</p>
        <p>文章内容</p>
        <!--使用footer定义文章底部信息-->
        <footer>
            footer
        </footer>
    </article>
</section>
<!--使用aside定义侧边栏信息-->
<aside>
    <header>

    </header>
    <nav>
        <ul>
            <li><a href="#">aside</a></li>
            <li><a href="#">aside</a></li>
            <li><a href="#">aside</a></li>
            <li><a href="#">aside</a></li>
        </ul>
    </nav>
</aside>
<!--使用footer定义页面页脚-->
<footer>
    footer
</footer>
</body>
</html>
